/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import { AuthService, authService } from './AuthService'
import { UsersService, usersService } from './UsersService'
import { ExpensesService, expensesService } from './ExpensesService'
import { InflowsService, inflowsService } from './InflowsService'
export type Services = {
  auth: AuthService
  users: UsersService
  expenses: ExpensesService
  inflows: InflowsService
}
export const services = {
  auth: authService,
  users: usersService,
  expenses: expensesService,
  inflows: inflowsService
} as const
