name: Format

on:
  push:
    branches:
      - main
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.js"
      - "**.mjs"
      - "**.cs"
      - "**.json"
      - ".github/workflows/**.yml"

jobs:
  format-backend:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "expensify-backend/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./expensify-backend
        run: pnpm install

      - name: Run Prettier Format
        working-directory: ./expensify-backend
        run: pnpm code:prettier:format

      - name: Commit changes
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --quiet && ! git diff --staged --quiet; then
            git commit -m "style: format backend code"
            git pull --rebase origin main
            git push
          fi

  format-frontend:
    runs-on: ubuntu-latest
    needs: format-backend

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "expensify-frontend/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./expensify-frontend
        run: pnpm install

      - name: Run Prettier Format
        working-directory: ./expensify-frontend
        run: pnpm code:prettier:format

      - name: Commit changes
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --quiet && ! git diff --staged --quiet; then
            git commit -m "style: format frontend code"
            git pull --rebase origin main
            git push
          fi
